//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMEntities : DbContext
    {
        public PMEntities()
            : base("name=PMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product_Monitor_Properties> Product_Monitor_Properties { get; set; }
        public virtual DbSet<Product_Order_Report> Product_Order_Report { get; set; }
        public virtual DbSet<Product_Order_Report_Warning> Product_Order_Report_Warning { get; set; }
        public virtual DbSet<V_PRODUCT_MONITOR_PROPERTIES> V_PRODUCT_MONITOR_PROPERTIES { get; set; }
        public virtual DbSet<V_PURCHASE_HISTORY_ATF> V_PURCHASE_HISTORY_ATF { get; set; }
        public virtual DbSet<V_STOCK_MONITOR> V_STOCK_MONITOR { get; set; }
        public virtual DbSet<STOCK> STOCKs { get; set; }
        public virtual DbSet<Stock_By_Date_ATF> Stock_By_Date_ATF { get; set; }
        public virtual DbSet<Stock_By_Date_History> Stock_By_Date_History { get; set; }
        public virtual DbSet<Product_Order_Report_Details> Product_Order_Report_Details { get; set; }
        public virtual DbSet<Products_Mix_Code> Products_Mix_Code { get; set; }
        public virtual DbSet<Products_Mix_Type> Products_Mix_Type { get; set; }
        public virtual DbSet<Products_Model> Products_Model { get; set; }
        public virtual DbSet<Products_Model_Detail> Products_Model_Detail { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Products_Alert_Day> Products_Alert_Day { get; set; }
        public virtual DbSet<Products_Customized> Products_Customized { get; set; }
    }
}
