//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Order_Report_Warning
    {
        public int Order_Detail_ID { get; set; }
        public int Warning_No { get; set; }
        public string Warning_Date { get; set; }
        public string Warning_Noted_Date { get; set; }
        public string Reason { get; set; }
    }
}
