//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Monitor_Properties
    {
        public string Product_Code { get; set; }
        public Nullable<double> Min_Stock { get; set; }
        public string Order_to { get; set; }
        public string Check_LP { get; set; }
        public string Check_TD { get; set; }
        public string Note_Unit_Convert { get; set; }
        public string Note_Purchase { get; set; }
        public string Vendor { get; set; }
        public string Note_Vendor { get; set; }
        public string Vendor_to_Purchase { get; set; }
        public string Operation_Detail { get; set; }
        public string Cost_Avg { get; set; }
        public string Cost_Note { get; set; }
        public string P0 { get; set; }
        public string P1 { get; set; }
        public string P2 { get; set; }
        public string P3 { get; set; }
        public string P_Note { get; set; }
        public string VAT { get; set; }
        public string S0 { get; set; }
        public string S1 { get; set; }
        public string S2 { get; set; }
        public string S3 { get; set; }
        public string S_Note { get; set; }
        public string QC_Form { get; set; }
    }
}
