//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Order_Report_Details
    {
        public int Datail_ID { get; set; }
        public string FDDATE { get; set; }
        public string Product_Code { get; set; }
        public string Product_Name { get; set; }
        public int Order_ID { get; set; }
        public int List_Num_Order { get; set; }
        public Nullable<double> P_Amount { get; set; }
        public string PUnit_Name { get; set; }
        public string Order_to { get; set; }
        public string End_Date { get; set; }
        public string Date1 { get; set; }
        public string Date2 { get; set; }
        public string Date3 { get; set; }
        public string Date4 { get; set; }
        public string Date5 { get; set; }
        public string Properties_Detail { get; set; }
        public string Operation_Detail { get; set; }
        public Nullable<double> Suggest_Order { get; set; }
        public string SUnit_Name { get; set; }
        public Nullable<double> Min_Stock { get; set; }
        public Nullable<double> TD_QTY { get; set; }
        public Nullable<double> LP_QTY { get; set; }
        public Nullable<double> TOTAL_QTY { get; set; }
        public string Vendor { get; set; }
        public string Note_Vendor { get; set; }
        public string Purchase_Name { get; set; }
        public string P0 { get; set; }
        public string P1 { get; set; }
        public string P2 { get; set; }
        public string P3 { get; set; }
        public string P_Note { get; set; }
        public Nullable<byte> Order_Status { get; set; }
        public string Note_Close { get; set; }
        public string closeDate { get; set; }
        public Nullable<int> Alert_ID { get; set; }
    }
}
