//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        public string FCDATASER { get; set; }
        public string FCUDATE { get; set; }
        public string FCUTIME { get; set; }
        public string FCLUPDAPP { get; set; }
        public string FCBAKYRHIS { get; set; }
        public string FCCORP { get; set; }
        public string FCBRANCH { get; set; }
        public string FCWHOUSE { get; set; }
        public string FCPROD { get; set; }
        public string FCLOT { get; set; }
        public string FDDATE { get; set; }
        public decimal FNAVGCOST { get; set; }
        public decimal FNQTY { get; set; }
        public decimal FNSTQTYSTD { get; set; }
        public decimal FNPRICE { get; set; }
        public decimal FNEDPRICE { get; set; }
        public decimal FNCOST { get; set; }
        public string FCCREATETY { get; set; }
        public string FCEAFTERR { get; set; }
        public string FCSELTAG { get; set; }
        public string FTDATETIME { get; set; }
        public int FIMILLISEC { get; set; }
        public string FCSKID { get; set; }
        public decimal FNUNQCQTY { get; set; }
        public decimal FNUNDOQTY { get; set; }
        public decimal FNSOALLOCQ { get; set; }
        public string FCGAG { get; set; }
        public string FDMFGDATE { get; set; }
        public string FDEXPIRE { get; set; }
        public decimal FNDOQTY { get; set; }
        public decimal FNGRNQTY { get; set; }
        public string FTLASTUPD { get; set; }
        public string FTLASTEDIT { get; set; }
        public decimal FNALLOCQTY { get; set; }
        public string FCCREATEAP { get; set; }
        public string FDRECDATE { get; set; }
        public string FCLOCATION { get; set; }
        public string FCSTORE { get; set; }
    }
}
