//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_By_Date_ATF
    {
        public string FCPROD { get; set; }
        public string FDDATE { get; set; }
        public string FCWHOUSE { get; set; }
        public decimal FNAVGCOST { get; set; }
        public decimal FNQTY { get; set; }
        public string Product_Code { get; set; }
        public string FTLASTUD { get; set; }
    }
}
