//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PURCHASE_HISTORY_ATF
    {
        public string PRODUCT_CODE { get; set; }
        public string PURCHASE_DATE { get; set; }
        public string VENDOR_CODE { get; set; }
        public string VENDOR_NAME { get; set; }
        public decimal QTY { get; set; }
        public decimal PRICE { get; set; }
        public string DISCOUNT_STR { get; set; }
        public decimal VAT_RATE { get; set; }
        public string FCSKID { get; set; }
    }
}
