//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_STOCK_MONITOR
    {
        public string PRODUCT_CODE { get; set; }
        public string FDDATE { get; set; }
        public Nullable<decimal> LP_QTY { get; set; }
        public Nullable<decimal> TD_QTY { get; set; }
        public Nullable<decimal> TOTAL_QTY { get; set; }
        public string P_FDDATE { get; set; }
        public Nullable<decimal> P_LP_QTY { get; set; }
        public Nullable<decimal> P_TD_QTY { get; set; }
        public Nullable<decimal> P_TOTAL_QTY { get; set; }
        public decimal DIFF_LP_QTY { get; set; }
        public decimal DIFF_TD_QTY { get; set; }
    }
}
